services:
  app-next:
    container_name: app-next
    restart: always
    image: ghcr.io/vatsim-radar/vatsim-radar/next
    depends_on:
      redis:
        condition: service_started
      db-next:
        condition: service_healthy
    ports:
      - 8080:3000
    volumes:
      - /opt/radar-next-data:/radar/src/data

  worker:
    build:
      context: .
      dockerfile: .config/dev.Dockerfile
    image: ghcr.io/vatsim-radar/vatsim-radar/next
    container_name: app-worker
    command: /radar/.config/worker.sh
    volumes:
      - /opt/radar-next-data:/radar/src/data
    depends_on:
      db-next:
        condition: service_healthy
      redis:
        condition: service_started
      app-next:
        condition: service_healthy

  redis:
    image: redis
    command: redis-server --requirepass RADAR
    expose:
      - 6379
    environment:
      - REDIS_APPLICATION_MODE=master

  db-next:
    image: mysql
    restart: always
    container_name: db-next
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=radar
      - MYSQL_ROOT_PASSWORD=localhost
    ports:
      - '3307:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      interval: 5s
      retries: 40
    volumes:
      - /opt/db-next:/var/lib/mysql
