services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      #- 8080:80
      - 80:80
